
version: '3.8'

services:

  php:
    container_name: php82
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html      
    build:
      context: .
      dockerfile: DockerFile

  database:
    container_name: mysql80
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: next_docker_cours
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - 8001:80